// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb0xom1cm2e5xSWjhGpWXXkbxPgGh6Eu8',
    appId: '1:77121574140:web:943d889091aaa23a593379',
    messagingSenderId: '77121574140',
    projectId: 'helpcity-e76e0',
    authDomain: 'helpcity-e76e0.firebaseapp.com',
    databaseURL: 'https://helpcity-e76e0-default-rtdb.firebaseio.com',
    storageBucket: 'helpcity-e76e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGOsUhBoKZSm2_7Ir9OBDNOle_XGGXB0I',
    appId: '1:77121574140:android:73bf60566ae74e1c593379',
    messagingSenderId: '77121574140',
    projectId: 'helpcity-e76e0',
    databaseURL: 'https://helpcity-e76e0-default-rtdb.firebaseio.com',
    storageBucket: 'helpcity-e76e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm6bAJuOMSoktp07KmzWLx81TaOdlcasw',
    appId: '1:77121574140:ios:b5fd9f59659a6773593379',
    messagingSenderId: '77121574140',
    projectId: 'helpcity-e76e0',
    databaseURL: 'https://helpcity-e76e0-default-rtdb.firebaseio.com',
    storageBucket: 'helpcity-e76e0.appspot.com',
    iosBundleId: 'com.example.hpcty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm6bAJuOMSoktp07KmzWLx81TaOdlcasw',
    appId: '1:77121574140:ios:92a9b6c3f88d862e593379',
    messagingSenderId: '77121574140',
    projectId: 'helpcity-e76e0',
    databaseURL: 'https://helpcity-e76e0-default-rtdb.firebaseio.com',
    storageBucket: 'helpcity-e76e0.appspot.com',
    iosBundleId: 'com.example.hpcty.RunnerTests',
  );
}
